### ISSUE TITLE
Support JIRA 7.0+ and JIRA Cloud

### ISSUE THREAD

**Issue by kevinschumacher** [trentm/jirash#28]
I know this is a heavy lift, but Atlassian deprecated the SOAP and XML RPC API in JIRA 6, and removed it in JIRA 7 and JIRA Cloud. 

https://developer.atlassian.com/jiradev/latest-updates/soap-and-xml-rpc-api-deprecation-notice

It would be great to update this to support the newer JIRA REST APIs. 

This is a migration guide provided by Atlassian:
https://developer.atlassian.com/jiradev/latest-updates/soap-and-xml-rpc-api-deprecation-notice/jira-soap-to-rest-migration-guide

**Comment by kevinschumacher** [comment]
FYI this is the error that occurs if you're trying to run it against a JIRA 7 server:



```
$ jirash filters

Traceback (most recent call last):
  File "/Users/kevinschumacher/jirash/lib/jirashell.py", line 1307, in <module>
    retval = main(sys.argv)
  File "/Users/kevinschumacher/jirash/lib/jirashell.py", line 1302, in main
    return shell.main(argv, loop=cmdln.LOOP_IF_EMPTY)
  File "/Users/kevinschumacher/jirash/lib/cmdln.py", line 259, in main
    return self.cmd(args)
  File "/Users/kevinschumacher/jirash/lib/cmdln.py", line 277, in cmd
    retval = self.onecmd(argv)
  File "/Users/kevinschumacher/jirash/lib/cmdln.py", line 412, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/Users/kevinschumacher/jirash/lib/cmdln.py", line 1115, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/Users/kevinschumacher/jirash/lib/jirashell.py", line 581, in do_filters
    filters = self.jira.filters()
  File "/Users/kevinschumacher/jirash/lib/jirashell.py", line 547, in jira
    self.cfg[self.jira_url]["password"])
  File "/Users/kevinschumacher/jirash/lib/jirashell.py", line 90, in __init__
    self.auth = self.server.jira1.login(username, password)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
ProtocolError: <ProtocolError for jira.example.com/rpc/xmlrpc: 404 Not Found>

Python: 2.7.9 (default, Feb 10 2015, 03:28:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
OS: Darwin-15.6.0-x86_64-i386-64bit
```

**Comment by trentm** [comment]
@kevinschumacher I've started re-writing jirash in node.js (`npm install -g jirash`). It is using a recent JIRA REST API now. Are you able to try that out... if this is still relevant for you?

**Comment by trentm** [comment]
I'm closing because this is so old now. jirash v2 (first released 2017-11-10) should, I think. jirash v2 works against the Jira v8.7.1 we use at my work.
