### ISSUE TITLE
jirash blew up: expired session from long 'jirash>' shell

### ISSUE THREAD

**Issue by mcavage** [trentm/jirash#5]
```
()
Traceback (most recent call last):
  File "/Users/mark/jirash/lib/jirashell.py", line 986, in <module>
    retval = main(sys.argv)
  File "/Users/mark/jirash/lib/jirashell.py", line 981, in main
    return shell.main(argv, loop=cmdln.LOOP_IF_EMPTY)
  File "/Users/mark/jirash/lib/cmdln.py", line 261, in main
    return self.cmdloop()
  File "/Users/mark/jirash/lib/cmdln.py", line 348, in cmdloop
    retval = self.onecmd(argv)
  File "/Users/mark/jirash/lib/cmdln.py", line 412, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/Users/mark/jirash/lib/cmdln.py", line 1115, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/Users/mark/jirash/lib/jirashell.py", line 781, in do_createissue
    issue = self.jira.create_issue(data)
  File "/Users/mark/jirash/lib/jirashell.py", line 387, in create_issue
    return self.server.jira1.createIssue(self.auth, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1570, in __request
    verbose=self.__verbose
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1468, in parse_response
    return u.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 0: 'java.lang.Exception: com.atlassian.jira.rpc.exception.RemoteAuthenticationException: User not authenticated yet, or session timed out.'>

Python: 2.7.1 (r271:86832, Jul 31 2011, 19:30:53) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)]
OS: ('Darwin', 'bluesnoop', '11.4.0', 'Darwin Kernel Version 11.4.0: Mon Apr  9 19:32:15 PDT 2012; root:xnu-1699.26.8~1/RELEASE_X86_64', 'x86_64')

* * * * * * * * * * * * * * * * * * * * * * * *
* Please log a bug at                         *
*    https://github.com/trentm/jirash/issues  *
* to report this error. Thanks!               *
* -- Trent                                    *
* * * * * * * * * * * * * * * * * * * * * * * *
```

**Comment by trentm** [comment]
jirash v2 (first released 2017-11-10) was re-written in node.js. This issue is for jirash v1, which is no longer supported so I'm closing this as "won't fix".
