### ISSUE TITLE
jirash blows up when resolving a ticket that's already resolved.

### ISSUE THREAD

**Issue by mcavage** [trentm/jirash#7]
```
jirash resolve OS-1670
()
Traceback (most recent call last):
 File "/home/mcavage/work/jirash/lib/jirashell.py", line 986, in <module>
   retval = main(sys.argv)
 File "/home/mcavage/work/jirash/lib/jirashell.py", line 981, in main
   return shell.main(argv, loop=cmdln.LOOP_IF_EMPTY)
 File "/home/mcavage/work/jirash/lib/cmdln.py", line 259, in main
   return self.cmd(args)
 File "/home/mcavage/work/jirash/lib/cmdln.py", line 277, in cmd
   retval = self.onecmd(argv)
 File "/home/mcavage/work/jirash/lib/cmdln.py", line 412, in onecmd
   return self._dispatch_cmd(handler, argv)
 File "/home/mcavage/work/jirash/lib/cmdln.py", line 1115, in _dispatch_cmd
   return handler(argv[0], opts, *args)
 File "/home/mcavage/work/jirash/lib/jirashell.py", line 809, in do_resolve
   self.jira.resolve(key)
 File "/home/mcavage/work/jirash/lib/jirashell.py", line 358, in resolve
   res = self._jira_soap_call("progressWorkflowAction", [key, "5"])
 File "/home/mcavage/work/jirash/lib/jirashell.py", line 97, in _jira_soap_call
   out = getattr(server, methodName)(*authedArgs)
 File "/home/mcavage/work/jirash/deps/SOAPpy/Client.py", line 540, in __call__
   return self.__r_call(*args, **kw)
 File "/home/mcavage/work/jirash/deps/SOAPpy/Client.py", line 562, in __r_call
   self.__hd, self.__ma)
 File "/home/mcavage/work/jirash/deps/SOAPpy/Client.py", line 475, in __call
   raise p
faultType: <Fault soapenv:Server.userException: com.atlassian.jira.rpc.exception.RemoteException: Error occurred when running workflow action Resolve Issue: 
Errors: {}
Error Messages: [Action 5 is invalid]: <SOAPpy.Types.structType detail at 150378284>: {'hostname': 'devhub', 'com.atlassian.jira.rpc.exception.RemoteException': ''}>

Python: 2.7.2 (default, Mar 23 2012, 13:45:04) 
[GCC 4.6.2]
OS: ('SunOS', 'martin', '5.11', 'joyent_20120921T180038Z', 'i86pc')

* * * * * * * * * * * * * * * * * * * * * * * *
* Please log a bug at                         *
*    https://github.com/trentm/jirash/issues  *
* to report this error. Thanks!               *
* -- Trent                                    *
* * * * * * * * * * * * * * * * * * * * * * * *
```

**Comment by trentm** [comment]
jirash v2 (first released 2017-11-10) was re-written in node.js. This issue is for jirash v1, which is no longer supported so I'm closing this as "won't fix".
