### ISSUE TITLE
Blow up on search on a non-existant Project

### ISSUE THREAD

**Issue by cobracmder** [trentm/jirash#9]
[2013-106-10:57:32]
[~]
carlos@Lrrr:% jirash issues -p IMAGES ubuntu

Traceback (most recent call last):
  File "/Users/carlos/working/gh-public/jirash/lib/jirashell.py", line 1006, in <module>
    retval = main(sys.argv)
  File "/Users/carlos/working/gh-public/jirash/lib/jirashell.py", line 1001, in main
    return shell.main(argv, loop=cmdln.LOOP_IF_EMPTY)
  File "/Users/carlos/working/gh-public/jirash/lib/cmdln.py", line 259, in main
    return self.cmd(args)
  File "/Users/carlos/working/gh-public/jirash/lib/cmdln.py", line 277, in cmd
    retval = self.onecmd(argv)
  File "/Users/carlos/working/gh-public/jirash/lib/cmdln.py", line 412, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/Users/carlos/working/gh-public/jirash/lib/cmdln.py", line 1115, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/Users/carlos/working/gh-public/jirash/lib/jirashell.py", line 635, in do_issues
    project_keys=opts.project_keys)
  File "/Users/carlos/working/gh-public/jirash/lib/jirashell.py", line 232, in issues_from_search
    self.auth, project_keys, terms, BIG)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1575, in __request
    verbose=self.__verbose
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 0: 'java.lang.Exception: java.lang.NullPointerException'>

Python: 2.7.2 (default, Oct 11 2012, 20:14:37) 
[GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)]
OS: ('Darwin', 'Lrrr.local', '12.3.0', 'Darwin Kernel Version 12.3.0: Sun Jan  6 22:37:10 PST 2013; root:xnu-2050.22.13~1/RELEASE_X86_64', 'x86_64')

**Comment by trentm** [comment]
jirash v2 (first released 2017-11-10) was re-written in node.js. This issue is for jirash v1, which is no longer supported so I'm closing this as "won't fix".
